packages:
  - apps/*
  - packages/*

publicHoistPattern:
  - "*react*"
  - "better-sqlite3"
  - "*.node"
  - "yaml"
  - "electron"
  - "esbuild"
  - "commander"
  - "chalk"
  - "uuid"

ignoredBuiltDependencies:
  - better-sqlite3
  - esbuild
